services:
  db:
    image: postgres:latest
    volumes:
      - ./dockerConfig/postgres-dev-init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: five-champions
    ports:
      - 5432:5432
